#!/bin/sh

source "$HOME"/.config/rofi/applets/shared/theme.bash
theme="$type/$style"

efonts="JetBrains Mono Nerd Font 12"

rofi -theme-str "listview {columns: 1; lines: 6;}" \
    -theme-str 'textbox-prompt-colon {str: "󱒄 ";}' \
    -theme-str "element-text {font: \"$efonts\";}" \
    -theme-str "window {width: 600px;}" \
    -dmenu \
    -i \
    -theme ${theme} $@
