general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 540
    on-timeout = hyprctl hyprsunset gamma 10
    on-resume = hyprctl hyprsunset gamma 80
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && hyprctl hyprsunset gamma 80
}
